name: 'Hello Docker Action'
description: 'Greet someone'
author: 'octocat@github.com'

inputs:
  my_name:
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  greeting:
    description: 'Full greeting'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.my_name }}

branding:
  icon: 'mic'
  color: 'purple'
