name: Python CI
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize Python Environment
        # Format: {owner}/{repo}@{ref}
        uses: waelkdouh/python-setup@main
        with:
          python-version: '3.10'

      - name: Run Tests
        run: pytest
